name: ridgebox
favicon: null
layout_spectrum: 0.23116239509545267
typography_spectrum: 0.9459840217605233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.15306759695522487
  lightness: 0.948527314234525
  saturation: 0.8008332669269294
  rhythmicContrast: 0.1722262199036777
purpose: []
